# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  linkFarm,
  fetchurl,
  runCommandLocal,
  zig_0_16,
  name ? "zig-packages",
}:
let
  unpackZigArtifact =
    {
      name,
      artifact,
    }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig_0_16 ];
      }
      ''
        # workaround https://codeberg.org/ziglang/zig/issues/31866
        # https://github.com/Cloudef/zig2nix/issues/54
        touch "$TMPDIR/build.zig"
        hash="$(cd "$TMPDIR" && zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
        mv "$TMPDIR/p/$hash.tar.gz" "$out"
        chmod 755 "$out"
      '';

  fetchZigArtifact =
    {
      name,
      url,
      hash,
    }:
    let
      artifact = fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };
in
linkFarm name [
  {
    name = "gobject_codegen-0.3.1-B33qzayBBwCzgdHS0OPxMtEVdwyL7jQgC0P4-NRplt0C";
    path = fetchZigArtifact {
      name = "gobject_codegen";
      url = "git+https://github.com/ianprime0509/zig-gobject#97caf8bfb4386409aab1160f7ec05c32ee6d5d7d";
      hash = "sha256-Ue6OcgCJfcOIZP+L30eKpQg4QK68B2mzmvoGSBhfiJY=";
    };
  }
  {
    name = "xml-0.2.0-ZTbP3yI6AgB9Rpd2hQrueO63ib0Bm6mQiL_WB1t7JAmP";
    path = fetchZigArtifact {
      name = "xml";
      url = "git+https://github.com/ianprime0509/zig-xml?ref=main#b97f2ab4868ae3cac9902b33a40d3f31d2df739d";
      hash = "sha256-zhh38L8X+8Zk83HsXTpZ/yRp5bPT5QgizB5QlmdtcYQ=";
    };
  }
]
